### ISSUE TITLE
Looks like Deno setup doesn't work

### ISSUE THREAD

**Issue by kaievns** [evan-liu/karabiner.ts#99]
Maybe I'm holding it wrong, but I thought I'd report this

```
deno run  --allow-env --allow-read --allow-write main.ts         
error: Uncaught ReferenceError: require is not defined
    return require('node:path').join(
    ^
    at Object.karabinerConfigFile (https://deno.land/x/karabinerts@1.24.0/output.ts:16:5)
    at writeToProfile (https://deno.land/x/karabinerts@1.24.0/output.ts:61:51)
    at file:///Users/kai/projects/karabiner/main.ts:13:1
```

looks like the output thing tries to import `node:path` and barfs. everything else seem working 

```
console.log(rule("stuff").manipulators([...]).build())
```

this works fine

**Comment by kaievns** [comment]
as a workaround, I did this

```js
console.log(JSON.stringify({
  title: "My rules",
  rules: [
    rule("..."),
    ....
  ]
}, null, 2);
```

and then build it like so:

```
deno run main.ts > output.json
```

and then import it manually in karabiner

**Comment by evan-liu** [comment]
Hi @kaievns , thanks for trying out the project. Are you importing from `deno.ts` like

`import { rule, writeToProfile } from 'https://deno.land/x/karabinerts@{version}/deno.ts'`

**Comment by kaievns** [comment]
yup, exactly that

```js
import {
  ifDevice,
  map,
  rule,
  writeToProfile,
} from "https://deno.land/x/karabinerts@1.24.0/index.ts";

import { halmak } from "./halmak.ts";

const ifInternalKeyboard = ifDevice({ vendor_id: 1452, product_id: 834 });
const ifExternalKaiboard = ifDevice({ vendor_id: 7504, product_id: 24926 });

writeToProfile("Default", [
  rule("internal-halmak", ifInternalKeyboard).manipulators([
    halmak,
  ]),
  rule("kaiboard-controls-swap", ifExternalKaiboard).manipulators([
    map("left⌘").to("left⌃"),
    map("left⌃").to("left⌘"),
    map("right⌘").to("right⌃"),
    map("right⌃").to("right⌘"),
  ]),
]);
```

**Comment by evan-liu** [comment]
looks like you are importing from `index.ts` instead of `deno.ts`

```typescript
import {
  ifDevice,
  map,
  rule,
  writeToProfile,
} from "https://deno.land/x/karabinerts@1.24.0/deno.ts";
```

**Comment by kaievns** [comment]
ah! thank you!
